env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - google
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2021
  sourceType: module
  project: ['./tsconfig.json']
plugins:
  - react
rules: {
         "react/prop-types": "off"
}
settings:
  react:
    version: detect
